config/routes.rb
EmployeeReporter::Application.routes.draw do
  devise_for :users

  resources :reports

  root 'reports#new'

end

app/models/report.rb
class Report < ActiveRecord::Base
  extend Enumerize

  belongs_to :user, inverse_of: :reports

  scope :latest, order('created_at DESC').limit(1)
  scope :since_last_monday, -> { where("created_at >= ?", Chronic.parse('last Monday')) }

  validates :question1, presence: true
  validates :question2, presence: true
  validates :question3, presence: true
  validates :question4, presence: true
  validates :mood, inclusion: { in: %w(1 2 3) }

  enumerize :mood, in: [1,2,3]

  before_validation :sanitize_multi_inputs
  before_save :serialize_multi_inputs
  after_save :check_for_summary_email
  after_save :deserialize_multi_inputs

  def self.send_summary_email
    reports = []
    User.all_ids.each do |user_id|
      reports << Report.latest.where( user_id: user_id ).first
    end

    ReportMailer.summary_report(reports).deliver
  end

  # TODO find scheduler and call this method every friday when reminders need to be sent out
  def self.send_reminders
    User.without_report.each do |user|
      ReportMailer.employee_reminder(user).deliver
    end
  end

  private
    def serialize_multi_inputs
      4.times do |i|
        n = i+1
        send "question#{n}=", send("question#{n}").to_json
      end
    end
    def deserialize_multi_inputs
      4.times do |i|
        n = i+1
        send "question#{n}=", ActiveSupport::JSON.decode(send("question#{n}"))
      end
    end

    # remove empty elements
    def sanitize_multi_inputs
      4.times do |i|
        n = i+1
        sanitized_array = send("question#{n}").select { |element| !element.empty? }
        send "question#{n}=", (sanitized_array.empty? ? nil : sanitized_array)
      end
    end

    def check_for_summary_email
      Report.send_summary_email if User.without_report.count <= 0
    end

    def jsonify array
      sanitized_array =
      sanitized_array.to_json
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reports, inverse_of: :user

  def self.without_report
    all.select { |user| user.reports.since_last_monday.empty? }
  end

  def self.all_ids
    select(:id).all.map { |user| user.id }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < InheritedResources::Base
  actions :new, :create

  before_filter :authenticate_user!
  before_filter :add_user_association, only: :create

  private
    def add_user_association
      build_resource.user = current_user
    end

    def permitted_params
      params.permit report: [ { question1: [], question2: [], question3: [], question4: [] }, :mood ]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/report_mailer_helper.rb
module ReportMailerHelper
  def mood_to_smiley mood
    case mood.to_i
    when 1
      ":-)"
    when 2
      ":-|"
    when 3
      ":-("
    else
      "?"
    end
  end

  def average_mood_from reports
    moods = reports.map { |report| report.mood.to_f }
    (moods.reduce(:+).to_f / moods.size.to_f).round
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "EmployeeReporter"
    %meta{ charset: "utf-8" }
    %meta{ "http-equiv" => 'X-UA-Compatible', content: 'IE=Edge,chrome=1' }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    = csrf_meta_tags
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true

    -# For third-generation iPad with high-resolution Retina display:
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'

    -# For iPhone with high-resolution Retina display:
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'

    -# For first- and second-generation iPad:
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'

    -# For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

    -# For all other devices
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

    = javascript_include_tag "application", "data-turbolinks-track" => true

  %body

    %div{ class: "navbar navbar-fluid-top" }
      %div{ class: "navbar-inner" }
        %div{ class: "container-fluid" }
          %a{ class: "btn btn-navbar", "data-target" => ".nav-collapse", "data-toggle" => "collapse" }
            %span{ class: "icon-bar" }
            %span{ class: "icon-bar" }
            %span{ class: "icon-bar" }

          %a{ class: "brand", href: "#" } Employee Report
          %div{ class: "container-fluid nav-collapse" }
            %ul{ class: "nav" }
              - if current_user
                %li= link_to "New Report", new_report_path
                %li= link_to "Edit Account", edit_user_registration_path
                %li= link_to "Logout", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Login", new_user_session_path
                %li= link_to "Register", new_user_registration_path

    %div{ class: "container-fluid" }
      %div{ class: "row-fluid" }
        %div{ class: "span9" }
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Arkavis 2014

app/views/reports/new.html.haml
%h1
  = t 'report.new_heading'

= simple_form_for resource, url: { action: :create }, html: {class: 'form-vertical' } do |f|
  - 4.times do |i|
    - n = i+1
    - answers = resource.send("question#{n}")
    - if answers.is_a? Array
      - answers.each_with_index do |answer, j|
        - if j == 0
          = f.input :"question#{n}", input_html: { class: 'multi_answer', name: "report[question#{n}][]", value: answer }
        - else
          = f.text_field :"question#{n}", { class: 'multi_answer', name: "report[question#{n}][]", id: nil, value: answer }
          %br

    - else
      = f.input :"question#{n}", input_html: { class: 'multi_answer', name: "report[question#{n}][]" }

  %div.control-group{class: (resource.errors[:mood].empty? ? nil : 'error')}
    In general I feel ...
    %br
    = f.collection_radio_buttons :mood, [[1, fa_icon('smile-o')], [2, fa_icon('meh-o')], [3, fa_icon('frown-o')]], :first, :last
    = f.full_error :mood

  = f.button :submit